spring:
  application:
    name: weverse-order-event

  datasource:
    url: jdbc:mysql://172.23.44.210:3306/weverse_order?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: 172.23.44.210:9092
    consumer:
      group-id: weverse-order-group
      auto-offset-reset: earliest

  data:
    redis:
      host: 172.23.44.210
      port: 6379

kafka:
  topics:
    order: order-topic
    order-dead-letter: order-dead-letter-topic
    order-notification: order-notification-topic
    claim: claim-topic
    membership: membership-topic

server:
  port: 8080